name: API Tests
on:
  pull_request:
    branches:
      - main

jobs:
  api-test:
    runs-on: ubuntu-latest

    env:
      DEVELOPMENT: true
      STRIPE_SECRET_KEY: dummy_id
      STRIPE_PLATFORM_ACCOUNT: dummy_id
      STRIPE_WEBHOOK_SECRET: dummy_id
      JWT_SECRET: some123
      APPLE_MOBILE_CLIENT_ID: some_app
      GOOGLE_ANDROID_CLIENT_ID: dummy_id
      GOOGLE_IOS_CLIENT_ID: dummy_id
      UPLOAD_MAX_SIZE_MB: 15
      DB_NAMESPACE: test
      DB_DATABASE: test
      DB_USERNAME: test
      DB_PASSWORD: test
      DB_URL: ws://localhost:8000
      GOOGLE_CLOUD_STORAGE_BUCKET: media
      GOOGLE_CLOUD_STORAGE_ENDPOINT: http://localhost:4443
      SENDGRID_API_KEY: some_key
      SENDGRID_API_URL: http://localhost:3000/v3/mail/send
      NO_REPLY_EMAIL: no-reply@domain.com
      EMAIL_CODE_TIME_TO_LIVE: 10
      SENTRY_PROJECT_LINK: dummy_link
      PAYPAL_CLIENT_ID: dummy_id
      PAYPAL_CLIENT_KEY: dummy_key
      PAYPAL_WEBHOOK_ID: dummy_id

    services:
      surrealdb:
        image: surrealdb/surrealdb:latest
        ports:
          - "8000:8000"
        env:
          SURREAL_USER: test
          SURREAL_PASS: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: sleep 5
      - run: cargo test
