name: API Tests
on:
  pull_request:
    branches:
      - main

jobs:
  api-test:
    runs-on: ubuntu-latest

    env:
      START_PASSWORD: 12334
      DEVELOPMENT: true
      STRIPE_SECRET_KEY: dummy_id
      STRIPE_PLATFORM_ACCOUNT: dummy_id
      STRIPE_WEBHOOK_SECRET: dummy_id
      JWT_SECRET: some123
      APPLE_MOBILE_CLIENT_ID: some_app
      GOOGLE_ANDROID_CLIENT_ID: dummy_id
      GOOGLE_IOS_CLIENT_ID: dummy_id
      UPLOAD_MAX_SIZE_MB: 15
      DB_NAMESPACE: ${{ secrets.DB_NAMESPACE }}
      DB_DATABASE: test
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_URL: ${{ secrets.DB_URL }}
      GOOGLE_CLOUD_STORAGE_BUCKET: media
      GOOGLE_CLOUD_STORAGE_ENDPOINT: http://localhost:4443
      SENDGRID_API_KEY: some_key
      SENDGRID_API_URL: http://localhost:3000/v3/mail/send
      NO_REPLY_EMAIL: no-reply@domain.com
      EMAIL_CODE_TIME_TO_LIVE: 10
      SENTRY_PROJECT_LINK: dummy_link
      PAYPAL_CLIENT_ID: dummy_id
      PAYPAL_CLIENT_KEY: dummy_key
      PAYPAL_WEBHOOK_ID: dummy_id

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: sleep 5
      - run: cargo test
