name: API Tests
on:
  pull_request:
    branches:
      - main

jobs:
  api-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: mv .env.test .env
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - run: curl -sSL https://just.systems/install.sh | bash -s -- --to /usr/local/bin
      - run: just test
